name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -e .[dev]
      - name: Run tests
        run: |
          pytest -q